scss_files: '_scss/**/*.scss'

exclude:
    - _scss/functions.scss
    - _scss/base/grid.scss
    - _scss/base/poole.scss
    - _scss/dependencies/normalize.scss
    - _scss/dependencies/syntax.scss

linters:
    Indentation:
        width: 4

    PropertySortOrder:
        order:
            - position
            - top
            - right
            - bottom
            - left
            - z-index
            - display
            - float
            - flex-flow
            - flex-direction
            - flex-wrap
            - justify-content
            - align-items
            - align-content
            - order
            - flex
            - flex-grow
            - flex-shrink
            - flex-basis
            - align-self
            - columns
            - column-width
            - column-count
            - column-gap
            - column-rule
            - column-rule-width
            - column-rule-style
            - column-rule-color
            - break-before
            - break-after
            - break-inside
            - column-span
            - column-fill
            - box-sizing
            - width
            - height
            - min-width
            - max-width
            - min-height
            - max-height
            - padding
            - padding-top
            - padding-right
            - padding-bottom
            - padding-left
            - border
            - border-collapse
            - border-top
            - border-right
            - border-bottom
            - border-left
            - border-width
            - border-top-width
            - border-right-width
            - border-bottom-width
            - border-left-width
            - border-style
            - border-top-style
            - border-right-style
            - border-bottom-style
            - border-left-style
            - border-color
            - border-top-color
            - border-right-color
            - border-bottom-color
            - border-left-color
            - border-radius
            - border-top-right-radius
            - border-bottom-right-radius
            - border-bottom-left-radius
            - border-top-left-radius
            - border-image
            - border-image-source
            - border-image-slice
            - border-image-width
            - border-image-outset
            - border-image-repeat
            - border-spacing
            - margin
            - margin-top
            - margin-right
            - margin-bottom
            - margin-left
            - outline
            - outline-color
            - outline-style
            - outline-width
            - outline-offset
            - overflow
            - overflow-x
            - overflow-y
            - clip
            - box-decoration-break
            - clear
            - vertical-align
            - background
            - background-color
            - background-image
            - background-position
            - background-size
            - background-repeat
            - background-origin
            - background-clip
            - background-attachment
            - box-shadow
            - color
            - visibility
            - opacity
            - filter
            - appearance
            - cursor
            - pointer-events
            - user-select
            - content
            - direction
            - unicode-bidi
            - writing-mode
            - font
            - font-smoothing
            - osx-font-smoothing
            - font-family
            - src
            - font-size
            - font-size-adjust
            - font-weight
            - font-style
            - font-stretch
            - font-variant
            - hyphens
            - letter-spacing
            - word-spacing
            - line-height
            - text-size-adjust
            - text-rendering
            - text-align
            - text-align-last
            - text-justify
            - text-indent
            - text-decoration
            - text-emphasis
            - text-emphasis-style
            - text-emphasis-color
            - text-emphasis-position
            - text-transform
            - text-shadow
            - text-overflow
            - white-space
            - word-wrap
            - word-break
            - tab-size
            - list-style
            - list-style-type
            - list-style-position
            - list-style-image
            - counter-reset
            - counter-increment
            - table-layout
            - caption-side
            - empty-cell
            - quotes"
            - resize
            - image-rendering
            - -ms-interpolation-mode
            - perspective
            - perspective-origin
            - zoom
            - transition
            - transition-delay
            - transition-duration
            - transition-property
            - transition-timing-function
            - transform
            - transform-origin
            - transform-style
            - animation
            - animation-name
            - animation-duration
            - animation-timing-function
            - animation-delay
            - animation-iteration-count
            - animation-direction
            - animation-play-state
            - animation-fill-mode
            - backface-visibility
            - azimuth
            - elevation
            - voice-family
            - pitch
            - pitch-range
            - richness
            - speech-rate
            - volume
            - cue
            - cue-before
            - cue-after
            - pause
            - pause-before
            - pause-after
            - play-during
            - speak
            - speak-header
            - speak-numeral
            - speak-punctuation
            - stress
            - size
            - page-break-before
            - page-break-after
            - page-break-inside
            - orphans
            - widows