# For jekyll-stitch-plus(uglify js or not)
env: 'development'

# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The Traveling Twins
tagline:          The Blog
description:      Blog for The Traveling Twins
url:              http://blog.ttwns.tw

google_analytics_id: UA-35010205-2

paginate:         1

# Assets
sass:
  sass_dir:       _scss
  style:          :compressed

stitch:
  dependencies:
    - 'js/iconic.min.js'
    - 'js/functions.js'
  output: 'js/main.js'

# Defaults
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"

# Serving
host: 0.0.0.0
