# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The Traveling Twins
tagline:          The Blog
description:      Blog for The Traveling Twins
url:              http://blog.ttwns.tw

paginate:         1
