# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The Traveling Twins
tagline:          The Blog
description:      Blog for The Traveling Twins
url:              http://blog.ttwns.tw

google_analytics_id: UA-35010205-2

paginate:         1

# Assets
sass:
  sass_dir:       _scss
  style:          :compressed

# Defaults
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - octopress-autoprefixer
