# Site
title:            The Traveling Twins
subtitle:         The Blog
description:      Blog for The Traveling Twins
url:              http://blog.ttwns.tw

# Writing
new_post_name: :year-:month-:day-:title.md
post_asset_folder: true

# Pagination
per_page: 0

# Extensions
theme: ttwns

# SASS
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false