source 'https://rubygems.org'

gem 'jekyll'
gem 'html-proofer'
gem 'scss-lint'
gem 'overcommit'
gem 'guard'
gem 'guard-jekyll-plus'
gem 'guard-livereload'
gem 'rouge'
gem 'jekyll-stitch-plus'
gem 'uglifier'

gem 'octopress-hooks'
gem 'autoprefixer-rails'
